version: '3'
services:
  web:
    build: ./web
    volumes:
      - ./web/downloads:/var/www/downloads/
      - ./web/:/usr/src/app
    links:
      - redis
    restart: unless-stopped

  redis:
    image: redis
    command: redis-server
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - "8000:80"
      - "6800:6800"
    links:
      - web
    restart: unless-stopped
